# Generated by Django 3.1.4 on 2020-12-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('designation', models.CharField(blank=True, choices=[('SDE', 'SOFTWARE DEVELOPMENT ENGINEER'), ('SSE', 'SENIOR SOFTWARE ENGINEER')], max_length=10, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
